### ISSUE TITLE
Can't find Java path

### ISSUE THREAD

**Issue by KorbsStudio** [MrShieh-X/console-minecraft-launcher#12]
![image](https://user-images.githubusercontent.com/51213244/167716180-1e8f576a-2b9d-422d-aee9-00a2e862fb6c.png)

**Comment by KorbsStudio** [comment]
![image](https://user-images.githubusercontent.com/51213244/167717148-c565be78-e3f5-4f50-b8f3-8d548dfff1ba.png)
Never mind, it was on "fc35" instead of "fc36". This is probably becase I updated to Fedora 36 today.

**Comment by MrShieh-X** [comment]
Note your modification command:
`java -jar CMCL.jar 1.18.2 -config javaPath ...`

You have entered `java -jar CMCL.jar 1.18.2`, which means to start the game with version name "1.18.2", however, your "-config javaPath ..." after it will be ignored.

So, the correct modification command should be `java -jar CMCL.jar -config javaPath <Java path>` instead of "1.18.2"

So, it is not your Java problem
